### ISSUE TITLE
Directory ignore list not updated properly via context menu

### ISSUE THREAD

**Issue by rcjan** [hxseven/Remove-Empty-Directories#2]
If you add directories to the ignore list via the context menu, the entries will be added to the list (visible in GUI), but won't actually be used. Rescanning does not honor the additions and closing the app removes the entries completely. A workaround is manually modifying the text box after adding the ignore.

The problem is this piece of code:

```
private void proToolStripMenuItem_Click(object sender, EventArgs e)
    {
        if (this.tvFolders.SelectedNode == null) return;
        this.tcMain.SelectedIndex = 1;

        // TODO: Find a better way...
        this.btnDelete.Enabled = false;
        this.tbIgnoreFolders.AppendText("\r\n" + ((DirectoryInfo)this.tvFolders.SelectedNode.Tag).FullName);
    }
```

You're only adding the ignore to the text box, but the data binding is not updating the actual bound data. Didn't bother to look into the binding you did, I'm sure it's an easy fix for you ;)

**Comment by Walkman100** [comment]
Oh so it's not just me
I've noticed sometimes the entries adding doesn't work, hadn't narrowed it down to specifically the context menu

**Comment by hxseven** [comment]
Ah okay, I see. Thank you rcjan for debugging this, great work! :+1:
I will fix this in the next release. I just don't know when I will have time to work on the next release, because I'm super busy at the moment :neutral_face:

**Comment by nishantgupta204** [comment]
Hi,
I just debugged the code. The ignore list is showing the updated list even when we are closing and reopening the GUI. The problem I see here is we are allowing to add the already ignored folder to ignored list. It just creates the append the folder path. As far as I am concerned Add to ignore list menu item should be disabled for folders that are already ignored. Correct me if am I wrong here.

**Comment by hxseven** [comment]
Found the problem and fixed it :) I made the mistake to only update the GUI element but not the data binding config that is connected to the GUI textbox. See commit 488983b.
