### ISSUE TITLE
Folder deletion very slow

### ISSUE THREAD

**Issue by RevZero** [hxseven/Remove-Empty-Directories#20]
The scan for empty folders was pretty fast. It found 365 folders in a couple of seconds. When I started the deletion however, it only deleted about 2-3 folders per second. So it easily takes several minutes to delete a couple of hundred folders.
I haven't looked at the code, but shouldn't it take only several milliseconds to delete a folder or is there something special going on?

**Comment by jsytniak** [comment]
There is a setting on the settings user interface that controls the amount
of delay between deletes operations.

**Comment by RevZero** [comment]
Oh, never mind then. Thanks for the pointer, this wasn't so obvious.
